[package]
name = "stourney"
version = "0.0.3"
edition = "2021"
license = "MIT"
keywords = ["splendor", "game", "tournament", "manager"]
description = "Splendor tournament manager - an app for running Splendor tournaments between autonomous agents"
readme = "README.md"
repository = "https://github.com/pashneal/stourney_scripts"

[dependencies]
